# Generated by Django 4.0.2 on 2023-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='establisedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
