# Generated by Django 4.0.2 on 2023-06-30 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employers_establiseddate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_industry_state_rename_location_jobscreated_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Location',
        ),
        migrations.CreateModel(
            name='AvailableJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('salary', models.PositiveIntegerField(default=35000)),
                ('requirements', models.TextField()),
                ('ideal_candidate', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=200, null=True)),
                ('employers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employers')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.industry')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AvailableJobs',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.availablejobs'),
        ),
        migrations.DeleteModel(
            name='JobsCreated',
        ),
    ]
